apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-numbers-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-numbers-worker
  template:
    metadata:
      labels:
        app: add-numbers-worker
    spec:
      containers:
        - name: worker
          image: ${IMAGE_PREFIX}/worker:${TAG}
          env:
            - name: RABBITMQ_HOST
              value: messaging
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASSWORD
              value: "${RABBITMQ_PASSWORD}"
            - name: WORKER_QUEUE
              value: hackathon.add-numbers
